#pragma once

enum class ErrorCode {
    OK,
    WIFI_NOT_INITIALIZED,
    WIFI_NOT_CONNECTED,
    STATE_NOT_ALLOCATED,
    MQTT_CLIENT_NOT_CREATED,
    DNS_CLIENT_NOT_INITIALIZED_OR_INVALID_HOSTNAME,
    TLS_CONFIG_NOT_INITIALIZED,
    TLS_NOT_CONNECTED,
    MQTT_PUBLISH_ERROR,
    MQTT_PUBLISH_BUFFER_EMPTY,
    MQTT_PUBLISH_TOPIC_EMPTY,
    MQTT_SUBSCRIPTION_ERROR,
    OBSERVER_ALREADY_ATTACHED,
    OBSERVER_ALREADY_DETACHED,
    NOTIFIER_NOT_SET,
    UPDATE_TOPIC_EMPTY,
    UPDATE_DATA_EMPTY,
};